version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: dockerfiles/api_local.dockerfile
    container_name: mlops_api
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ../models:/models
    networks:
      monitoring:
        aliases:
          - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
    networks:
      monitoring:
        aliases:
          - prometheus
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      monitoring:
        aliases:
          - grafana
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  locust:
    image: locustio/locust
    container_name: locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust_tests.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --host http://api:8000
    networks:
      - monitoring
    depends_on:
      - api

networks:
  monitoring:
    driver: bridge
    name: monitoring_network

volumes:
  prometheus_data:
  grafana_data: 