global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mlops_api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics/'
    scrape_interval: 5s  # More frequent for API monitoring
    # Add some relabeling to make metrics more readable
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(.+)$'
        target_label: metric_name
        replacement: '$1' 